"""rename cols in users table

Revision ID: 3e68ad495969
Revises: c06321c0067f
Create Date: 2025-08-01 10:10:42.677651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e68ad495969'
down_revision: Union[str, None] = 'c06321c0067f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_contact', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('default_location', sa.String(length=50), nullable=True))
    op.drop_column('users', 'contact')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('contact', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'default_location')
    op.drop_column('users', 'default_contact')
    # ### end Alembic commands ###
