"""refreshing tables

Revision ID: 45fd5b255095
Revises: b867d373aa71
Create Date: 2024-11-27 19:41:29.909658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45fd5b255095'
down_revision: Union[str, None] = 'b867d373aa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detailedInfo_postNumb', table_name='detailedinfo')
    op.drop_table('detailedinfo')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_marketInfo_sphere', table_name='marketinfo')
    op.drop_table('marketinfo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketinfo',
    sa.Column('postNumb', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('sphere', mysql.FLOAT(), nullable=True),
    sa.Column('flagged', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('postNumb'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_marketInfo_sphere', 'marketinfo', ['sphere'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('flags', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defaultContact', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('defaultLocation', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('detailedinfo',
    sa.Column('postNumb', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flagged', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('prescription', mysql.JSON(), nullable=True),
    sa.Column('pseudoPrescription', mysql.FLOAT(), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('postNumb'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_detailedInfo_postNumb', 'detailedinfo', ['postNumb'], unique=False)
    # ### end Alembic commands ###
