"""updating tables to add imagecard

Revision ID: 629131b842de
Revises: cb70587aed2e
Create Date: 2025-05-04 15:54:30.026376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '629131b842de'
down_revision: Union[str, None] = 'cb70587aed2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_table('detailedinfo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detailedinfo',
    sa.Column('postNumb', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flagged', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('prescription', mysql.JSON(), nullable=True),
    sa.Column('pseudoPrescription', mysql.FLOAT(), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('postNumb'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('flags', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('defaultContact', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('defaultLocation', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('postNumb', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imagePath', mysql.VARCHAR(length=225), nullable=True),
    sa.ForeignKeyConstraint(['postNumb'], ['detailedinfo.postNumb'], name='images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
