"""change pseudoprescription to use float

Revision ID: a25ccfa00fbf
Revises: fe139607c8d1
Create Date: 2025-08-01 12:17:12.388645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a25ccfa00fbf'
down_revision: Union[str, None] = 'fe139607c8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailed_info', sa.Column('pseudo_prescription', sa.Float(), nullable=True))
    op.drop_column('detailed_info', 'pseudoPrescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detailed_info', sa.Column('pseudoPrescription', mysql.FLOAT(), nullable=True))
    op.drop_column('detailed_info', 'pseudo_prescription')
    # ### end Alembic commands ###
