"""update user column names

Revision ID: b568d3267655
Revises: b1b73851f2ad
Create Date: 2025-08-07 11:16:00.462109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b568d3267655'
down_revision: Union[str, None] = 'b1b73851f2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=50), nullable=True))
    op.drop_column('users', 'default_location')
    op.drop_column('users', 'default_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_contact', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('default_location', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'location')
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###
