"""remove p2

Revision ID: c06321c0067f
Revises: 30bac8aef662
Create Date: 2025-07-31 20:48:42.296427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c06321c0067f'
down_revision: Union[str, None] = '30bac8aef662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prescription', sa.JSON(), nullable=True))
    op.drop_column('users', 'prescription2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prescription2', mysql.JSON(), nullable=True))
    op.drop_column('users', 'prescription')
    # ### end Alembic commands ###
