"""initial schema

Revision ID: e36ad5a8d519
Revises: 
Create Date: 2025-09-15 22:42:58.865511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36ad5a8d519'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_info',
    sa.Column('post_numb', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('sphere', sa.Float(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('image_card', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('post_numb')
    )
    op.create_index(op.f('ix_market_info_sphere'), 'market_info', ['sphere'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=True),
    sa.Column('default_contact', sa.String(length=50), nullable=True),
    sa.Column('default_location', sa.String(length=50), nullable=True),
    sa.Column('prescription', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('detailed_info',
    sa.Column('post_numb', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('prescription', sa.JSON(), nullable=True),
    sa.Column('pseudo_prescription', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['post_numb'], ['market_info.post_numb'], ),
    sa.PrimaryKeyConstraint('post_numb')
    )
    op.create_index(op.f('ix_detailed_info_post_numb'), 'detailed_info', ['post_numb'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_numb', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['post_numb'], ['detailed_info.post_numb'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_index(op.f('ix_detailed_info_post_numb'), table_name='detailed_info')
    op.drop_table('detailed_info')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_market_info_sphere'), table_name='market_info')
    op.drop_table('market_info')
    # ### end Alembic commands ###
